import {
  FaCss3Alt,
  FaGithub,
  FaHtml5,
  FaNodeJs,
  FaPython,
  FaReact,
  IoLogoJavascript,
  SiChakraui,
  SiMongodb,
  SiPostman,
  SiRedux,
  SiTailwindcss,
  TbBrandNextjs,
} from "@utils/iconExp";
export const projectObj = [
  {
    name: "Ecommerce Site",
    imgUrl: "/sc.png",
    description:
      "Mollit ullamco velit culpa aliquip cupidatat duis Lorem in. In id et eiusmod quis non ullamco exercitation in ad. Tempor commodo laboris nisi incididunt eu cupidatat deserunt nisi laborum aliqua consequat minim. Tempor laborum fugiat velit mollit consequat ex. Eu duis qui mollit sit nostrud reprehenderit est laborum commodo deserunt.",
    projecturl: "http://eazy-shopping.vercel.app",
    gitsource: "https://github.com/GotameSafal/EazyShopping",
    technologies: [
      "html",
      "css",
      "js",
      "react",
      "nextjs",
      "python",
      "redux",
      "tailwind",
      "mongodb",
      "chakraui",
      "github",
      "nodejs",
    ],
  },
  {
    name: "Ecommerce Site",
    imgUrl: "/sc.png",
    description:
      "Mollit ullamco velit culpa aliquip cupidatat duis Lorem in. In id et eiusmod quis non ullamco exercitation in ad. Tempor commodo laboris nisi incididunt eu cupidatat deserunt nisi laborum aliqua consequat minim. Tempor laborum fugiat velit mollit consequat ex. Eu duis qui mollit sit nostrud reprehenderit est laborum commodo deserunt.",
    projecturl: "http://eazy-shopping.vercel.app",
    gitsource: "https://github.com/GotameSafal/EazyShopping",
    technologies: [
      "html",
      "css",
      "js",
      "react",
      "nextjs",
      "python",
      "redux",
      "tailwind",
      "mongodb",
      "chakraui",
      "github",
      "nodejs",
    ],
  },
];

export const nameWithIcons = {
  html: <FaHtml5 size={30} color="red" cursor="pointer" />,
  css: <FaCss3Alt size={30} color="#34517d" cursor="pointer" />,
  js: <IoLogoJavascript size={30} color="#f5ca3d" cursor="pointer" />,
  react: <FaReact size={30} color="#5ed3f3" cursor="pointer" />,
  nextjs: <TbBrandNextjs size={30} color="black" cursor="pointer" />,
  python: <FaPython size={30} color="#356c9b" cursor="pointer" />,
  redux: <SiRedux size={30} color="#7248b6" cursor="pointer" />,
  tailwind: <SiTailwindcss size={30} color="#38bdf8" cursor="pointer" />,
  mongodb: <SiMongodb size={30} color="#00ed63" cursor="pointer" />,
  chakraui: <SiChakraui size={30} color="rgb(72, 200, 194)" cursor="pointer" />,
  postman: <SiPostman size={30} color="#ff6c37" />,
  github: <FaGithub size={30} cursor="pointer" />,
  nodejs: <FaNodeJs size={30} cursor="pointer" />,
};
